sonar.projectKey=controle-financeiro
sonar.projectName=Controle Financeiro
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=node_modules/**,data/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info